#!/bin/bash
# /etc/init.d/roswifibot
source /opt/ros/fuerte/setup.bash
export ROS_PACKAGE_PATH=/home/wifibot/ros:$ROS_PACKAGE_PATH
# set path to launchfile
ROSLAUNCH_BIN="/opt/ros/fuerte/bin/roslaunch"
LAUNCHDIR="/home/wifibot/ros/roswifibot/launch/"
# carry out specific functions when asked by the system
case "$1" in
  start)
    echo "Starting roswifibot service ..."
    rospack profile
    $ROSLAUNCH_BIN $LAUNCHDIR/robot_launch.launch  \
      $LAUNCHDIR/joy_teleop.launch \
      $LAUNCHDIR/firewire.launch  \
      $LAUNCHDIR/hokuyo.launch &
    rosrun roswifibot beep.bash --odom --firewire --hokuyo &
    ;;
  stop)
    echo "Stopping roswifibot services ..."
    beep -f 200 -r 3 # tut tut tut
    pkill -f ros
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit 0
