#!/bin/bash
# /etc/init.d/roswifibot
source /opt/ros/fuerte/setup.bash
export ROS_PACKAGE_PATH=/home/wifibot/ros:$ROS_PACKAGE_PATH
#~ export ROS_IP=192.168.0.1
ROS_USER=wifibot
ROSLAUNCH_BIN="/opt/ros/fuerte/bin/roslaunch"
# set path to launchfile
# carry out specific functions when asked by the system
case "$1" in
  start)
    echo "Starting roswifibot service ..."
    rospack profile
    #~ su -c "$ROSLAUNCH_BIN /home/wifibot/ros/roswifibot/launch/robot_kinect_joy_launch.launch" $ROS_USER &
    $ROSLAUNCH_BIN /home/wifibot/ros/roswifibot/launch/robot_kinect_joy_launch.launch &
    ;;
  stop)
    pkill -f ros
    echo "Stopping roswifibot services ..."
    ;;
  restart)
    $0 stop
    sleep 3
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
exit 0
